### ISSUE TITLE
match by pattern is being override by extension

### ISSUE THREAD

**Issue by g0ld3lux** [tiagofumo/vim-nerdtree-syntax-highlight#11]
hi i have a patten for .blade.php
and the .php extension rule is over writing the pattern ...
i dont know if that is the normal behaviour can you help me out?
thanks

**Comment by tiagofumo** [comment]
@g0ld3lux please post all the plugin configuration lines in your .vimrc here

**Comment by tiagofumo** [comment]
@g0ld3lux I can't fully help you if I don't have more info about the configuration you are trying to use in your .vimrc. But I think what you are looking for is the configuration below:

```vim
let g:NERDTreePatternMatchHighlightColor = {} " necessary to prevent error
let g:NERDTreePatternMatchHighlightColor['.*\.blade\.php$'] = insert_color
```

Where `insert_color` is the 24-bit rgb hexadecimal color code of your choice (numbers only). E.g. `'00ff00'` for bright green.
