### ISSUE TITLE
Regex pattern-matching conflicting with extension-matching?

### ISSUE THREAD

**Issue by MrAvantiC** [tiagofumo/vim-nerdtree-syntax-highlight#12]
Hi,

first of all, thanks for your plugin!

I have an issue where I want all hidden files - so to say all files starting with a `.` - to have the same color.

Now I tried to acoomplish this with:
```
let s:red = "FC5C68"
let g:NERDTreePatternMatchHighlightColor['\..*'] = s:red
```
...unfortunately I get this as a result:
http://pasteboard.co/bNlsbjPH3.png

It feels like the file-extension of yml conflicts with my pattern. Although it might just be pattern that's at fault here, I'm not really a regex-expert. ;)

Any help would be appreciated!

**Comment by tiagofumo** [comment]
> Hi,
> first of all, thanks for your plugin!

Thank you :smiley:.

Sorry for the delay to answer, I don't remember receiving an email when this issue was opened.

I added a fix for this issue. If you update your plugin repo to sync with master it should be fine now. 

Thanks for contributing.
