### ISSUE TITLE
Execute coloring again

### ISSUE THREAD

**Issue by mike3run** [tiagofumo/vim-nerdtree-syntax-highlight#15]
I've noted that if i source my vimrc file again then the colors get lost, is there any function i call to re-color my nerdtree?

**Comment by ctaylo21** [comment]
+1

**Comment by hirokihokari** [comment]
+1

**Comment by ctaylo21** [comment]
I found a solution that works for me. I have this in my config file:

```
" Refresh vim-devicons to ensure they render properly (fixes render issues
" after sourcing config file)
if exists("g:loaded_webdevicons")
  call webdevicons#refresh()
endif
```

It's closer to the bottom of my config file but that may not matter.
