### ISSUE TITLE
Executable files

### ISSUE THREAD

**Issue by jorgehatccrma** [tiagofumo/vim-nerdtree-syntax-highlight#21]
This is not a bug report, but a question. How can I change the color of the executable files? I tried several combinations of regexs, along these lines:

    let g:NERDTreePatternMatchHighlightColor = {} " this line is needed to avoid error
    let g:NERDTreePatternMatchHighlightColor['.*\.sh[*]?$'] = "EA80FC"

but it only changes files ending in `.sh`, but not `.sh*` (the asterisk indicates an executable, as returned by `ls -lF`, which is what NERDTree uses, I believe)

**Comment by tiagofumo** [comment]
I am closing old issues. I fixed this, now executable files are highlighted like normal files (https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/commit/4aee945173480fb50c8e409f896c4397b5eac408). Any configuration you add to non-executable files will be working on executable files as well.
