### ISSUE TITLE
E117: Unknown function: <SNR>116_X

### ISSUE THREAD

**Issue by nomaed** [tiagofumo/vim-nerdtree-syntax-highlight#3]
While running in Tmux (2.3), I started getting errors:

```
Error detected while processing ~/.config/nvim/plugged/vim-nerdtree-syntax-highlight/after/syntax/nerdtree.vim:
line  373:
E117: Unknown function: <SNR>116_X
line  408:
E117: Unknown function: <SNR>116_X
```

It happens both on Ubuntu 16 and OS/X, when running inside Tmux (2.3), after enabling true-color support (with [these instructions](https://sunaku.github.io/tmux-24bit-color.html#usage)) using:
`set -ga terminal-overrides ",xterm-256color:Tc"`
and removing:
`set -g default-terminal "screen-256color"`
 from the config.

I have very little knowledge or experience in these realms, so please let me know what other debug information I can get for you so it'd help.

I can reliably reproduce the behavior, and revert it as well.
If I comment out the true-color `terminal-overrides` line and un-comment the original `default-terminal` line and restart tmux (`tmux kill-server`), everything works fine (but no true-color support in tmux), so this is a good way to reproduce this behavior.

**Comment by nomaed** [comment]
An update: This seems to happen when there is no `default-terminal` because tmux automatically sets it to `screen`. I don't know why would this cause the problem, since the 24-bit color mode IS actually being displayed (OS/X on iTerm2 and Ubuntu on Gnome Terminal). Vim is working fine with true color as well (NeoVim in my case).

**Comment by tiagofumo** [comment]
I'm trying to replicate the problem but I am not being able to. I downloaded and installed the latest version of tmux from the github repo. I use Gnome terminal on my Xubuntu 16.04.1. I don't use tmux normally and my default terminal is xterm-256color and I can get true color with tmux 2.1 (which is the one you will get if you install with apt-get) and also on the newest version from github (which I think would be 2.3?).

I also followed the steps in the blog post instructions you mentioned and I was able to get true color both in vim and outside of it. I use a perl script to test colors, if you are interested you can get the code [here](http://pastie.org/10925708) and create a .pl file with it. This is a screenshot:

![color test script screenshot](http://i.imgur.com/wsrojMI.png)

You can see that the "Tc" flag is true and all the colors look normal, which, like I said, is the same result I get if I don't follow the steps from the blog and just use xterm-256color on any version of tmux. This is a screenshot of my nerdtree in the tmux github project folder (I use [Neovim](https://neovim.io/)):

![nerdtree screenshot using tmux's Tc flag](http://i.imgur.com/3f9y3pR.png)

You can add something like:

`export TERM="xterm-256color"`

or 

`alias tmux="TERM=screen-256color-bce tmux"`

to your .bashrc if you want, or something similar to your .tmux.conf if you want to specify a TERM for tmux. 

Let me know if you have made any progress, but for now I am going to close this issue.

**Comment by nomaed** [comment]
I played a bit with the configuration and it seems that the problem has nothing to do with true or not true color modes, nor with tmux. 

The only difference is whether `$TERM` is set to `screen` or not.
If it's `xterm-256color` then everything is fine.
If it's `screen` then the errors are displayed, and no colors appear.

I can just do `export TERM=screen` (or in my case with fish, `set -gs TERM screen`) and even though NeoVim *is* showing normal color with `screen`, I get the errors.

So maybe it's not really a problem, although it's strange that NeoVim has no problem showing colors and has no errors with `screen`.

**Comment by tiagofumo** [comment]
@nomaed I found the bug now. An unnecessary if statement in the code I copied from a colorscheme was causing the function X to be undefined. The statement was:

`if has("gui_running") || &t_Co == 88 || &t_Co == 256`

But when `TERM=screen` the value of `&t_Co` is 8, so it would not go over the piece of code that declared the function X and caused the bug.

I pushed a simple fix to this bug. Thank you for opening the issue :+1: .
