### ISSUE TITLE
Vue components highlight

### ISSUE THREAD

**Issue by Rundik** [tiagofumo/vim-nerdtree-syntax-highlight#30]
I know I can do this

```vim
let g:NERDTreeExtensionHighlightColor = {}
let g:NERDTreeExtensionHighlightColor['vue'] = '42b883'
```

but having it by default would be great

**Comment by Rundik** [comment]
I found pull request for that https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/pull/28, but using official vue color (#42b883) would be even better

**Comment by tiagofumo** [comment]
Hi, sorry for the long response time. Unfortunately while I was adding new extensions that are now supported by vim-devicons, I added support for vuejs and didn't see this issue and your pull request. But I added that specific color (42b883) to the code on an extra commit. Thanks for the interest in the plugin.
