### ISSUE TITLE
Highlight full line when file name has spaces

### ISSUE THREAD

**Issue by norbert-op** [tiagofumo/vim-nerdtree-syntax-highlight#32]
Thanks for this extension, I like the results. I turned on this option, but only the last word before the extension is highlighted. Is there a way to configure it to recognize the whole file name when there are spaces? I'm a Windows user, and most of my file names have spaces.

```vim
	let g:NERDTreeFileExtensionHighlightFullName = 1
```

**Comment by tiagofumo** [comment]
Hi, sorry for the long response time. This was added on commit https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/commit/14f80ee177d971191f08911766bf0b7580062149 . Thanks for the interest in the plugin and the suggestion.

**Comment by norbert-op** [comment]
Thank you, the update looks great.
