### ISSUE TITLE
Wrong colors displayed in tree view 

### ISSUE THREAD

**Issue by cheap-glitch** [tiagofumo/vim-nerdtree-syntax-highlight#33]
Hi,
first thank you for this cool plugin! For the most part it works fine, but I found there are some filenames that are strangely reluctant. This is how I configured the plugin:
```vim
let g:NERDTreeSyntaxEnabledExtensions=[
	\'c',
	\'css',
	\'h',
	\'html',
	\'jpg',
	\'js',
	\'json',
	\'lock',
	\'md',
	\'php',
	\'png',
	\'pug',
	\'scss',
	\'vue'
\]

let s:lightgreen="8fbcbb"
let s:lightblue="88c0d0"
let s:pastelblue="81a1c1"
let s:blue="5e81ac"

let s:red="bf616a"
let s:orange="d08770"
let s:yellow="ebcb8b"
let s:green="a3be8c"
let s:purple="b48ead"

let g:NERDTreeExtensionHighlightColor={}
let g:NERDTreeExtensionHighlightColor['c']=s:blue
let g:NERDTreeExtensionHighlightColor['css']=s:blue
let g:NERDTreeExtensionHighlightColor['h']=s:blue
let g:NERDTreeExtensionHighlightColor['html']=s:pastelblue
let g:NERDTreeExtensionHighlightColor['jpg']=s:lightblue
let g:NERDTreeExtensionHighlightColor['js']=s:yellow
let g:NERDTreeExtensionHighlightColor['json']=s:orange
let g:NERDTreeExtensionHighlightColor['lock']=s:red
let g:NERDTreeExtensionHighlightColor['md']=s:lightgreen
let g:NERDTreeExtensionHighlightColor['php']=s:purple
let g:NERDTreeExtensionHighlightColor['png']=s:lightblue
let g:NERDTreeExtensionHighlightColor['pug']=s:lightgreen
let g:NERDTreeExtensionHighlightColor['scss']=s:blue
let g:NERDTreeExtensionHighlightColor['vue']=s:green

let g:NERDTreeExactMatchHighlightColor={}
let g:NERDTreeExactMatchHighlightColor['node_modules/']=s:lightblue
```
And the result is this:
![screenshot-1573664762](https://user-images.githubusercontent.com/46634000/68786636-69beb180-0640-11ea-9ad9-4b53b317836b.png)

The problem lies with the `scss` and `md` files. Although they are supposed to be highlighted in blue and light green respectively, that is not the case as you can see on the screenshot above.

I'm using gVim on Arch Linux. Is there some kind of setting that I missed? All these colors are part of the Nord theme I'm using, and they display fine in the source listings.

**Comment by tiagofumo** [comment]
Hey there, sorry for the very long reply time. This was a bug, that was just fixed with commit https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/commit/b2b3c0b7687a0d90c526a2378ecca486286b7d45 . Thanks for the feedback.
