### ISSUE TITLE
lag and customization 

### ISSUE THREAD

**Issue by mlwnvncnt** [tiagofumo/vim-nerdtree-syntax-highlight#40]
1)when i type vim., there is small lag and like first the files goes to right side then goes left and opens the tree there and in the right side an empty buffer is present.is there any way to remove this lag?

2) is there any way to remove the orange squares besides the folder icon?

![2020-10-14-171946_1920x1080_scrot](https://user-images.githubusercontent.com/50613933/95985672-7ba56780-0e42-11eb-8f65-7aba65946698.png)

**Comment by tiagofumo** [comment]
Hi @mlwnvncnt,

I am not sure that this plugin is causing any of the problems you related. This plugin only paints existing text on the NERDTree tab, it doesn't add any extra characters there. Those squares are normally a sign that some character is missing from the fonts you are using. That happens sometimes to me when I have the wrong font file from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts). I think the character that you are missing is the arrow that in front of the folder icon, which on the font file I am using is character u25B8 as you show in the picture.

**Comment by mlwnvncnt** [comment]
hello @tiagofumo ,
i removed the arrow from NERDTree config then the square stuff was removed, the font i am using is DroidSansMono Nerd Font Bold Italic, don't know why its not supporting it.The lag issue i am not able to figure out, its just a sec lag while starting, maybe directly related to NERDTree. Thanks for the quick reply.

**Comment by tiagofumo** [comment]
No problem @mlwnvncnt. I am going to close this issue now. Add a comment if you need anything else 👍
