### ISSUE TITLE
right side of the icons are not displayed

### ISSUE THREAD

**Issue by Mechap** [tiagofumo/vim-nerdtree-syntax-highlight#43]
![image](https://user-images.githubusercontent.com/54742369/102906115-77b24900-4474-11eb-8354-ce038be88a08.png)

**Comment by Mechap** [comment]
I'm using neovide which is a graphical user interface for neovim. I tried to set the guifont to nerdfont but it still doesn't render the icons properly. I tried to use the window terminal and it actually worked fine.

**Comment by jreeeedd** [comment]
I'm with the terminal and the icons doesn't render properly too.

**Comment by tiagofumo** [comment]
There is already an issue open about this on #8. I would recommend updating all the plugins you have to the latest version, and disabling this plugin to see if the problem persists. Then trying different font files. But anything else should be commented there.
