### ISSUE TITLE
Disable default highlights and enable selectively

### ISSUE THREAD

**Issue by mikekreeki** [tiagofumo/vim-nerdtree-syntax-highlight#7]
Is it currently possible to disable all default highlighting and set custom colors only for extensions I choose? For example as a programmer I'd like to make only `css` and `less` files dimmed as I don't work with them. They are in file structure, I don't want to hide them, just want to able to visually distinguish whats code and what are styles. Is something like that possible without all the default highlighting? 

Very nice plugin by the way 👍

**Comment by ryanoasis** [comment]
Cool idea

**Comment by tiagofumo** [comment]
With the new version you can now do this adding these lines to your .vimrc:
```vim
let g:NERDTreeSyntaxDisableDefaultExtensions = 1
let g:NERDTreeSyntaxEnabledExtensions = ['css', 'less']
```

**Comment by mikekreeki** [comment]
Looks good. Thank you! 👏
